import {StyleSheet, Platform} from "react-native";

const COLORS = {
  bg: '#0f0f1a',
  card: '#1a1a2e',
  cardBorder: '#2d2d44',
  accent: '#7c3aed',
  accentLight: '#a78bfa',
  accentGold: '#f59e0b',
  text: '#f0f0f0',
  textMuted: '#9ca3af',
  textDim: '#6b7280',
  success: '#4ade80',
  white: '#ffffff',
};

const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: COLORS.bg },
  keyboardContainer: { flex: 1 },
  scroll: { flex: 1 },
  scrollContent: { paddingTop: 10 },
  headerBar: {
    backgroundColor: COLORS.card,
    paddingHorizontal: 20,
    paddingVertical: 14,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: COLORS.cardBorder,
    elevation: 4,
    shadowColor: '#000',
    shadowOpacity: 0.3,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
  },
  headerTitle: { color: COLORS.white, fontSize: 18, fontWeight: '700', letterSpacing: 0.5 },
  switchRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  switchLabel: { color: COLORS.textMuted, fontSize: 12, fontWeight: '600' },
  // — Tab Navigation —
  tabContainer: {
    flexDirection: 'row',
    backgroundColor: COLORS.card,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.cardBorder,
  },
  tabButton: {
    flex: 1,
    paddingVertical: 10,
    marginHorizontal: 4,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#16213e',
    borderWidth: 1,
    borderColor: COLORS.cardBorder,
  },
  tabButtonActive: { backgroundColor: COLORS.accent, borderColor: COLORS.accent },
  tabText: { color: COLORS.textMuted, fontSize: 13, fontWeight: '600' },
  tabTextActive: { color: COLORS.white, fontWeight: '800' },
  // — Profile —
  profileSection: {
    alignItems: 'center',
    paddingVertical: 32,
    paddingHorizontal: 20,
    backgroundColor: COLORS.card,
    marginBottom: 16,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
    borderBottomWidth: 2,
    borderColor: COLORS.accent,
  },
  avatar: { width: 110, height: 110, borderRadius: 55, borderWidth: 3, borderColor: COLORS.accent, marginBottom: 8 },
  badge: {
    backgroundColor: '#052e16',
    borderWidth: 1,
    borderColor: COLORS.success,
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 20,
    marginBottom: 12,
  },
  badgeText: { color: COLORS.success, fontSize: 12, fontWeight: '700' },
  profileName: { color: COLORS.white, fontSize: 26, fontWeight: '800', textAlign: 'center' },
  profileTitle: { color: COLORS.accentLight, fontSize: 14, fontWeight: '600', marginTop: 4, marginBottom: 14, textAlign: 'center' },
  profileBio: { color: COLORS.textMuted, fontSize: 13, lineHeight: 20, textAlign: 'center', marginBottom: 16, paddingHorizontal: 8 },
  contactRow: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'center', gap: 8, marginBottom: 6 },
  contactItem: { color: COLORS.textMuted, fontSize: 12, textAlign: 'center', marginBottom: 4 },
  // — Social —
  socialRow: { flexDirection: 'row', gap: 12, marginTop: 16, marginBottom: 20 },
  socialBtn: {
    alignItems: 'center',
    backgroundColor: '#16213e',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.cardBorder,
  },
  socialIcon: { fontSize: 20, marginBottom: 4 },
  socialLabel: { color: COLORS.accentLight, fontSize: 11, fontWeight: '600' },
  // — Download —
  downloadBtn: {
    backgroundColor: COLORS.accent,
    paddingVertical: 14,
    paddingHorizontal: 36,
    borderRadius: 50,
    elevation: 4,
    shadowColor: COLORS.accent,
    shadowOpacity: 0.5,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 8,
  },
  downloadBtnPressed: { backgroundColor: '#5b21b6' },
  downloadBtnText: { color: COLORS.white, fontWeight: '700', fontSize: 14 },
  // — Section box —
  sectionBox: {
    marginHorizontal: 16,
    marginBottom: 16,
    backgroundColor: COLORS.card,
    borderRadius: 16,
    padding: 18,
    borderWidth: 1,
    borderColor: COLORS.cardBorder,
  },
  sectionTitle: { color: COLORS.white, fontSize: 17, fontWeight: '700', marginBottom: 4 },
  sectionSubtitle: { color: COLORS.textDim, fontSize: 11, fontStyle: 'italic', marginBottom: 16 },
  sectionHeader: {
    backgroundColor: '#0f172a',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    marginBottom: 8,
    borderLeftWidth: 3,
    borderLeftColor: COLORS.accent,
  },
  sectionHeaderText: { color: COLORS.accentLight, fontWeight: '700', fontSize: 13 },
  // — Skill card —
  skillCard: { backgroundColor: '#16213e', padding: 12, borderRadius: 10, borderWidth: 1, borderColor: COLORS.cardBorder },
  skillHeader: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 8 },
  skillName: { color: COLORS.text, fontWeight: '600', fontSize: 13 },
  skillPercent: { color: COLORS.accentLight, fontWeight: '700', fontSize: 13 },
  progressBg: { height: 6, backgroundColor: '#0f172a', borderRadius: 4, overflow: 'hidden' },
  progressFill: { height: 6, borderRadius: 4 },
  // — Timeline card —
  timelineCard: { flexDirection: 'row', backgroundColor: '#16213e', borderRadius: 12, padding: 14, borderWidth: 1, borderColor: COLORS.cardBorder },
  timelineDot: { width: 10, height: 10, borderRadius: 5, backgroundColor: COLORS.accent, marginTop: 4, marginRight: 12 },
  timelineContent: { flex: 1 },
  timelineRole: { color: COLORS.white, fontWeight: '700', fontSize: 14, marginBottom: 2 },
  timelineCompany: { color: COLORS.accentLight, fontSize: 13, marginBottom: 2 },
  timelinePeriod: { color: COLORS.textMuted, fontSize: 11, marginBottom: 6 },
  timelineHint: { color: COLORS.accentGold, fontSize: 11, fontStyle: 'italic' },
  // — Inputs —
  inputLabel: { color: COLORS.textMuted, fontSize: 12, fontWeight: '600', marginBottom: 6, marginTop: 4 },
  textInput: {
    backgroundColor: '#0f172a',
    color: COLORS.text,
    borderWidth: 1,
    borderColor: COLORS.cardBorder,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: Platform.OS === 'ios' ? 12 : 10,
    marginBottom: 14,
  },
  textArea: { minHeight: 120, textAlignVertical: 'top' },
  // — Loading —
  loadingRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingVertical: 12, gap: 12 },
  loadingText: { color: COLORS.textMuted, fontSize: 13 },
  // — Modal —
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.7)', justifyContent: 'flex-end' },
  modalBox: { backgroundColor: COLORS.card, borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 24, borderWidth: 1, borderColor: COLORS.cardBorder },
  modalTitle: { color: COLORS.white, fontSize: 20, fontWeight: '800', marginBottom: 6 },
  modalCompany: { color: COLORS.accentLight, fontSize: 15, fontWeight: '600', marginBottom: 8 },
  modalPeriod: { color: COLORS.textMuted, fontSize: 13 },
  modalDivider: { height: 1, backgroundColor: COLORS.cardBorder, marginVertical: 16 },
  modalDesc: { color: COLORS.text, fontSize: 14, lineHeight: 22, marginBottom: 20 },
  modalCloseBtn: { backgroundColor: COLORS.accent, paddingVertical: 13, borderRadius: 12, alignItems: 'center' },
  modalCloseBtnText: { color: COLORS.white, fontSize: 14, fontWeight: '700' },
});
export default styles;